version: '3'
services:
  sassy-apple:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - sassy-db
  sassy-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: janakiran
      POSTGRES_DB: sassyapple
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
